spring:
  profiles:
    active: local # 기본 활성화 profile

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  config-location: classpath:mapper/config/mapper-config.xml
  mapper-locations: classpath:mapper/login/*.xml
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  logging:
    level:
      root: debug
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://dev-server:3306/dev_db
    username: devuser
    password: devpass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  logging:
    level:
      root: info
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://prod-server:3306/prod_db
    username: produser
    password: prodpass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  logging:
    level:
      root: warn
